export default [
  {
    STD_YEAR: "2564",
    STD_TERM: "1",
    GRADE: [
      {
        F_ROWID_SUBJECT: "574be8fa5c281",
        SUBJECT_CODE: "GEHU103",
        SUBJECT_NAME: "ความจริงของชีวิต",
        VOLUME: "2",
        CREDIT: "3(3-0-6)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "-",
        CAL_VALUE: "-",
        ASSESSED: false,
      },
      {
        F_ROWID_SUBJECT: "5cb7fde6e99ec",
        SUBJECT_CODE: "TECE203",
        SUBJECT_NAME: "เทคนิคก่อสร้างอาคารและกฎหมายอาคาร",
        VOLUME: "1",
        CREDIT: "3(2-2-5)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "-",
        CAL_VALUE: "-",
        ASSESSED: false,
      },
      {
        F_ROWID_SUBJECT: "5cb7fc77547c9",
        SUBJECT_CODE: "TECE103",
        SUBJECT_NAME: "วัสดุก่อสร้างและการทดสอบ",
        VOLUME: "1",
        CREDIT: "3(1-4-4)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "-",
        CAL_VALUE: "-",
        ASSESSED: false,
      },
      {
        F_ROWID_SUBJECT: "5cb82012a1e1f",
        SUBJECT_CODE: "TECE204",
        SUBJECT_NAME: "เครื่องมือและเครื่องจักรกลงานก่อสร้าง",
        VOLUME: "1",
        CREDIT: "3(2-2-5)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "-",
        CAL_VALUE: "-",
        ASSESSED: false,
      },
      {
        F_ROWID_SUBJECT: "5cb7ff037e92a",
        SUBJECT_CODE: "TECE303",
        SUBJECT_NAME: "การประมาณราคาก่อสร้าง",
        VOLUME: "1",
        CREDIT: "3(3-0-6)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "-",
        CAL_VALUE: "-",
        ASSESSED: false,
      },
      {
        F_ROWID_SUBJECT: "5cb804939fa0e",
        SUBJECT_CODE: "TECE506",
        SUBJECT_NAME: "การออกแบบโครงสร้างคอนกรีตเสริมเหล็ก",
        VOLUME: "1",
        CREDIT: "3(2-2-5)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "-",
        CAL_VALUE: "-",
        ASSESSED: false,
      },
    ],
    GRADE_SUMMARY: [
      {
        YEAR: "2564",
        TERM: "1",
        CURRENT_CREDIT: "0",
        CURRENT_GPA: "0",
        TOTAL_CREDIT: "86",
        TOTAL_GPA: "3.06",
      },
    ],
  },
  {
    STD_YEAR: "2563",
    STD_TERM: "2",
    GRADE: [
      {
        F_ROWID_SUBJECT: "5cb7faba41709",
        SUBJECT_CODE: "TECE102",
        SUBJECT_NAME: "ปฏิบัติการเทคโนโลยีคอนกรีต",
        VOLUME: "1",
        CREDIT: "1(0-3-2)",
        TOTAL_CREDIT: "1",
        GRADE_CODE: "A",
        CAL_VALUE: "4",
        ASSESSED: true,
      },
      {
        F_ROWID_SUBJECT: "57723e743125a",
        SUBJECT_CODE: "TEET106",
        SUBJECT_NAME: "ความปลอดภัยและอาชีวอนามัยในสถานประกอบการ",
        VOLUME: "2",
        CREDIT: "3(3-0-6)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "A",
        CAL_VALUE: "4",
        ASSESSED: true,
      },
      {
        F_ROWID_SUBJECT: "574bfbec6c530",
        SUBJECT_CODE: "GESO102",
        SUBJECT_NAME: "การจัดการเพื่อคุณภาพชีวิต",
        VOLUME: "2",
        CREDIT: "3(3-0-6)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "B",
        CAL_VALUE: "3",
        ASSESSED: true,
      },
      {
        F_ROWID_SUBJECT: "5cb7fd840ca06",
        SUBJECT_CODE: "TECE202",
        SUBJECT_NAME: "การบริหารงานและตรวจงานก่อสร้าง",
        VOLUME: "1",
        CREDIT: "3(2-2-5)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "B",
        CAL_VALUE: "3",
        ASSESSED: true,
      },
      {
        F_ROWID_SUBJECT: "5cb821c818696",
        SUBJECT_CODE: "TECE508",
        SUBJECT_NAME: "ชลศาสตร์",
        VOLUME: "1",
        CREDIT: "3(2-2-5)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "B",
        CAL_VALUE: "3",
        ASSESSED: true,
      },
      {
        F_ROWID_SUBJECT: "574bdc711fc0f",
        SUBJECT_CODE: "GELA104",
        SUBJECT_NAME: "ภาษาอังกฤษเพื่อการสื่อสาร",
        VOLUME: "2",
        CREDIT: "3(3-0-6)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "C+",
        CAL_VALUE: "2.5",
        ASSESSED: true,
      },
      {
        F_ROWID_SUBJECT: "5cb7feb42462b",
        SUBJECT_CODE: "TECE302",
        SUBJECT_NAME: "เขียนแบบก่อสร้างด้วยคอมพิวเตอร์",
        VOLUME: "1",
        CREDIT: "3(1-4-4)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "C+",
        CAL_VALUE: "2.5",
        ASSESSED: true,
      },
      {
        F_ROWID_SUBJECT: "5cb7fa7434d22",
        SUBJECT_CODE: "TECE101",
        SUBJECT_NAME: "เทคโนโลยีคอนกรีต",
        VOLUME: "1",
        CREDIT: "3(3-0-6)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "I",
        CAL_VALUE: "0",
        ASSESSED: true,
      },
    ],
    GRADE_SUMMARY: [
      {
        YEAR: "2563",
        TERM: "2",
        CURRENT_CREDIT: "22",
        CURRENT_GPA: "3.05",
        TOTAL_CREDIT: "86",
        TOTAL_GPA: "3.06",
      },
    ],
  },
  {
    STD_YEAR: "2563",
    STD_TERM: "1",
    GRADE: [
      {
        F_ROWID_SUBJECT: "5cb80438bef52",
        SUBJECT_CODE: "TECE505",
        SUBJECT_NAME: "ปฏิบัติการปฐพีกลศาสตร์",
        VOLUME: "1",
        CREDIT: "1(0-3-2)",
        TOTAL_CREDIT: "1",
        GRADE_CODE: "A",
        CAL_VALUE: "4",
        ASSESSED: true,
      },
      {
        F_ROWID_SUBJECT: "574bef2f6b340",
        SUBJECT_CODE: "GESC103",
        SUBJECT_NAME: "เทคโนโลยีสารสนเทศเพื่อชีวิต",
        VOLUME: "2",
        CREDIT: "3(3-0-6)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "B+",
        CAL_VALUE: "3.5",
        ASSESSED: true,
      },
      {
        F_ROWID_SUBJECT: "574bf05d72cdb",
        SUBJECT_CODE: "GESC106",
        SUBJECT_NAME: "เทคโนโลยีตามแนวเศรษฐกิจพอเพียง",
        VOLUME: "2",
        CREDIT: "3(3-0-6)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "B+",
        CAL_VALUE: "3.5",
        ASSESSED: true,
      },
      {
        F_ROWID_SUBJECT: "57723db5cdb98",
        SUBJECT_CODE: "IDID101",
        SUBJECT_NAME: "การพัฒนาบุคลากรและการฝึกอบรมด้านเทคโนโลยี",
        VOLUME: "2",
        CREDIT: "3(2-3-6)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "B+",
        CAL_VALUE: "3.5",
        ASSESSED: true,
      },
      {
        F_ROWID_SUBJECT: "5cb7fe399d5ab",
        SUBJECT_CODE: "TECE301",
        SUBJECT_NAME: "เขียนแบบก่อสร้าง",
        VOLUME: "1",
        CREDIT: "3(1-4-4)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "B",
        CAL_VALUE: "3",
        ASSESSED: true,
      },
      {
        F_ROWID_SUBJECT: "5cb7ff5602644",
        SUBJECT_CODE: "TECE401",
        SUBJECT_NAME: "การจัดการงานระบบอุปกรณ์อาคารและสิ่งแวดล้อมในอาคาร",
        VOLUME: "1",
        CREDIT: "3(2-2-5)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "B",
        CAL_VALUE: "3",
        ASSESSED: true,
      },
      {
        F_ROWID_SUBJECT: "5cb803bf954ca",
        SUBJECT_CODE: "TECE503",
        SUBJECT_NAME: "การวิเคราะห์โครงสร้าง",
        VOLUME: "1",
        CREDIT: "3(3-0-6)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "B",
        CAL_VALUE: "3",
        ASSESSED: true,
      },
      {
        F_ROWID_SUBJECT: "5cb803f989728",
        SUBJECT_CODE: "TECE504",
        SUBJECT_NAME: "ปฐพีกลศาสตร์",
        VOLUME: "1",
        CREDIT: "3(3-0-6)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "B",
        CAL_VALUE: "3",
        ASSESSED: true,
      },
    ],
    GRADE_SUMMARY: [
      {
        YEAR: "2563",
        TERM: "1",
        CURRENT_CREDIT: "22",
        CURRENT_GPA: "3.25",
        TOTAL_CREDIT: "64",
        TOTAL_GPA: "3.06",
      },
    ],
  },
  {
    STD_YEAR: "2562",
    STD_TERM: "2",
    GRADE: [
      {
        F_ROWID_SUBJECT: "57723a25f0f84",
        SUBJECT_CODE: "MATH606",
        SUBJECT_NAME: "คณิตศาสตร์สำหรับเทคโนโลยีอุตสาหกรรม 2",
        VOLUME: "2",
        CREDIT: "3(3-0-6)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "B+",
        CAL_VALUE: "3.5",
        ASSESSED: true,
      },
      {
        F_ROWID_SUBJECT: "5774d56096ac9",
        SUBJECT_CODE: "STAT117",
        SUBJECT_NAME: "สถิติสำหรับเทคโนโลยีและอุตสาหกรรม",
        VOLUME: "2",
        CREDIT: "3(3-0-6)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "B+",
        CAL_VALUE: "3.5",
        ASSESSED: true,
      },
      {
        F_ROWID_SUBJECT: "5cb7fcc6db0de",
        SUBJECT_CODE: "TECE201",
        SUBJECT_NAME: "เทคโนโลยีงานสำรวจเพื่อการก่อสร้าง",
        VOLUME: "1",
        CREDIT: "3(1-4-4)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "B",
        CAL_VALUE: "3",
        ASSESSED: true,
      },
      {
        F_ROWID_SUBJECT: "57723d52b35a8",
        SUBJECT_CODE: "TEIC213",
        SUBJECT_NAME: "เทคโนโลยีสารสนเทศและคอมพิวเตอร์",
        VOLUME: "1",
        CREDIT: "3(2-3-6)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "B",
        CAL_VALUE: "3",
        ASSESSED: true,
      },
      {
        F_ROWID_SUBJECT: "574bc02bad7f5",
        SUBJECT_CODE: "GELA103",
        SUBJECT_NAME: "ทักษะการอ่านภาษาอังกฤษ",
        VOLUME: "2",
        CREDIT: "3(3-0-6)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "C+",
        CAL_VALUE: "2.5",
        ASSESSED: true,
      },
      {
        F_ROWID_SUBJECT: "5cb802fdd7ba4",
        SUBJECT_CODE: "TECE502",
        SUBJECT_NAME: "กลศาสตร์วัสดุ",
        VOLUME: "1",
        CREDIT: "3(2-2-5)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "C+",
        CAL_VALUE: "2.5",
        ASSESSED: true,
      },
      {
        F_ROWID_SUBJECT: "574bdad78f2dc",
        SUBJECT_CODE: "GELA101",
        SUBJECT_NAME: "ภาษาไทยเพื่อการสื่อสาร",
        VOLUME: "2",
        CREDIT: "3(3-0-6)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "D+",
        CAL_VALUE: "1.5",
        ASSESSED: true,
      },
    ],
    GRADE_SUMMARY: [
      {
        YEAR: "2562",
        TERM: "2",
        CURRENT_CREDIT: "21",
        CURRENT_GPA: "2.78",
        TOTAL_CREDIT: "42",
        TOTAL_GPA: "2.96",
      },
    ],
  },
  {
    STD_YEAR: "2562",
    STD_TERM: "1",
    GRADE: [
      {
        F_ROWID_SUBJECT: "574bf2817ef50",
        SUBJECT_CODE: "GESC109",
        SUBJECT_NAME: "พลังงานเพื่อชีวิต",
        VOLUME: "1",
        CREDIT: "3(3-0-6)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "B+",
        CAL_VALUE: "3.5",
        ASSESSED: true,
      },
      {
        F_ROWID_SUBJECT: "5774d4dab388a",
        SUBJECT_CODE: "MATH605",
        SUBJECT_NAME: "คณิตศาสตร์สำหรับเทคโนโลยีอุตสาหกรรม 1",
        VOLUME: "4",
        CREDIT: "3(3-0-6)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "B+",
        CAL_VALUE: "3.5",
        ASSESSED: true,
      },
      {
        F_ROWID_SUBJECT: "57723e16118b7",
        SUBJECT_CODE: "TEPT302",
        SUBJECT_NAME: "การฝึกปฏิบัติงานเทคโนโลยีพื้นฐาน",
        VOLUME: "2",
        CREDIT: "3(1-6-5)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "B+",
        CAL_VALUE: "3.5",
        ASSESSED: true,
      },
      {
        F_ROWID_SUBJECT: "574bf377dcb92",
        SUBJECT_CODE: "PHYS101",
        SUBJECT_NAME: "ฟิสิกส์เบื้องต้น",
        VOLUME: "2",
        CREDIT: "3(3-0-6)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "B",
        CAL_VALUE: "3",
        ASSESSED: true,
      },
      {
        F_ROWID_SUBJECT: "5cb802ba83109",
        SUBJECT_CODE: "TECE501",
        SUBJECT_NAME: "กลศาสตร์วิศวกรรม",
        VOLUME: "1",
        CREDIT: "3(3-0-6)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "B",
        CAL_VALUE: "3",
        ASSESSED: true,
      },
      {
        F_ROWID_SUBJECT: "57723f169b865",
        SUBJECT_CODE: "TECT114",
        SUBJECT_NAME: "การจัดการอุตสาหกรรม",
        VOLUME: "1",
        CREDIT: "3(2-2-5)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "B",
        CAL_VALUE: "3",
        ASSESSED: true,
      },
      {
        F_ROWID_SUBJECT: "57723f8a7a998",
        SUBJECT_CODE: "TEEC106",
        SUBJECT_NAME: "วัสดุอุตสาหกรรม",
        VOLUME: "2",
        CREDIT: "3(2-2-5)",
        TOTAL_CREDIT: "3",
        GRADE_CODE: "C+",
        CAL_VALUE: "2.5",
        ASSESSED: true,
      },
    ],
    GRADE_SUMMARY: [
      {
        YEAR: "2562",
        TERM: "1",
        CURRENT_CREDIT: "21",
        CURRENT_GPA: "3.14",
        TOTAL_CREDIT: "21",
        TOTAL_GPA: "3.14",
      },
    ],
  },
];
