export default  [
  {
    F_ROWID_REGIS_D: "60b352ef28524",
    F_ROWID_SUBJECT: "574bf05d72cdb",
    F_ROWID_TABTEACH: "TTI12564118425",
    YEAR: "2564",
    TERM: "1",
    SUBJECT_CODE: "GESC106",
    SECTION: "06",
    REGIS_TYPE: "C",
    REGIS_TYPE_TEXT: "Credit",
    SUBJECT_NAME: "เทคโนโลยีตามแนวเศรษฐกิจพอเพียง",
    SUBJECT_TYPE: "ภาคปกติ",
    CREDIT: "3(3-0-6)",
    TOTAL_CREDIT: "3",
    T_HOUR: "3",
    P_HOUR: "0",
    S_HOUR: "6",
    STATUS: "00",
    STATUS_TEXT: null,
    VOLUME: "2",
    DAY_CODE: "1",
    DAY_NAME: "จ.",
    ROOM_CODE: "14503",
    TIME_FROM: "09:00",
    TIME_TO: "12:00",
    PERIOD_START: "2",
    PERIOD_END: "4",
    Q1: "L",
    TEACHER: [
      {
        TEACHER_CODE: "141001",
        FIRST_THAI_NAME: "สุชิรา",
        LAST_THAI_NAME: "นวลกำแหง",
      },
    ],
  },
  {
    F_ROWID_REGIS_D: "60b352ef2a35b",
    F_ROWID_SUBJECT: "57723db5cdb98",
    F_ROWID_TABTEACH: "TTI12564119583",
    YEAR: "2564",
    TERM: "1",
    SUBJECT_CODE: "IDID101",
    SECTION: "02",
    REGIS_TYPE: "C",
    REGIS_TYPE_TEXT: "Credit",
    SUBJECT_NAME: "การพัฒนาบุคลากรและการฝึกอบรมด้านเทคโนโลยี",
    SUBJECT_TYPE: "ภาคปกติ",
    CREDIT: "3(2-3-6)",
    TOTAL_CREDIT: "3",
    T_HOUR: "2",
    P_HOUR: "3",
    S_HOUR: "6",
    STATUS: "00",
    STATUS_TEXT: null,
    VOLUME: "2",
    DAY_CODE: "4",
    DAY_NAME: "พฤ.",
    ROOM_CODE: "18/3204",
    TIME_FROM: "13:00",
    TIME_TO: "18:00",
    PERIOD_START: "5",
    PERIOD_END: "9",
    Q1: "S",
    TEACHER: [
      {
        TEACHER_CODE: "137004",
        FIRST_THAI_NAME: "พิศุทธิ์",
        LAST_THAI_NAME: "บัวเปรม",
      },
      {
        TEACHER_CODE: "141001",
        FIRST_THAI_NAME: "สุชิรา",
        LAST_THAI_NAME: "นวลกำแหง",
      },
    ],
  },
  {
    F_ROWID_REGIS_D: "60b352ef2c0b0",
    F_ROWID_SUBJECT: "5cb7fe399d5ab",
    F_ROWID_TABTEACH: "TTI12564119592",
    YEAR: "2564",
    TERM: "1",
    SUBJECT_CODE: "TECE301",
    SECTION: "01",
    REGIS_TYPE: "C",
    REGIS_TYPE_TEXT: "Credit",
    SUBJECT_NAME: "เขียนแบบก่อสร้าง",
    SUBJECT_TYPE: "ภาคปกติ",
    CREDIT: "3(1-4-4)",
    TOTAL_CREDIT: "3",
    T_HOUR: "1",
    P_HOUR: "4",
    S_HOUR: "4",
    STATUS: "00",
    STATUS_TEXT: null,
    VOLUME: "1",
    DAY_CODE: "2",
    DAY_NAME: "อ.",
    ROOM_CODE: "18/3205",
    TIME_FROM: "13:00",
    TIME_TO: "18:00",
    PERIOD_START: "5",
    PERIOD_END: "9",
    Q1: "L",
    TEACHER: [
      {
        TEACHER_CODE: "656300",
        FIRST_THAI_NAME: "เดชา",
        LAST_THAI_NAME: "ด้วงมาก",
      },
    ],
  },
  {
    F_ROWID_REGIS_D: "60b352ef2dbb1",
    F_ROWID_SUBJECT: "5cb7ff5602644",
    F_ROWID_TABTEACH: "TTI12564119596",
    YEAR: "2564",
    TERM: "1",
    SUBJECT_CODE: "TECE401",
    SECTION: "01",
    REGIS_TYPE: "C",
    REGIS_TYPE_TEXT: "Credit",
    SUBJECT_NAME: "การจัดการงานระบบอุปกรณ์อาคารและสิ่งแวดล้อมในอาคาร",
    SUBJECT_TYPE: "ภาคปกติ",
    CREDIT: "3(2-2-5)",
    TOTAL_CREDIT: "3",
    T_HOUR: "2",
    P_HOUR: "2",
    S_HOUR: "5",
    STATUS: "00",
    STATUS_TEXT: null,
    VOLUME: "1",
    DAY_CODE: "2",
    DAY_NAME: "อ.",
    ROOM_CODE: "18/3203",
    TIME_FROM: "08:00",
    TIME_TO: "12:00",
    PERIOD_START: "1",
    PERIOD_END: "4",
    Q1: "S",
    TEACHER: [
      {
        TEACHER_CODE: "654049",
        FIRST_THAI_NAME: "เอนกพงศ์",
        LAST_THAI_NAME: "ธรรมาธิวัฒน์",
      },
      {
        TEACHER_CODE: "656300",
        FIRST_THAI_NAME: "เดชา",
        LAST_THAI_NAME: "ด้วงมาก",
      },
    ],
  },
  {
    F_ROWID_REGIS_D: "60b352ef2f8dd",
    F_ROWID_SUBJECT: "5cb803bf954ca",
    F_ROWID_TABTEACH: "TTI12564119599",
    YEAR: "2564",
    TERM: "1",
    SUBJECT_CODE: "TECE503",
    SECTION: "01",
    REGIS_TYPE: "C",
    REGIS_TYPE_TEXT: "Credit",
    SUBJECT_NAME: "การวิเคราะห์โครงสร้าง",
    SUBJECT_TYPE: "ภาคปกติ",
    CREDIT: "3(3-0-6)",
    TOTAL_CREDIT: "3",
    T_HOUR: "3",
    P_HOUR: "0",
    S_HOUR: "6",
    STATUS: "00",
    STATUS_TEXT: null,
    VOLUME: "1",
    DAY_CODE: "4",
    DAY_NAME: "พฤ.",
    ROOM_CODE: "18/3205",
    TIME_FROM: "09:00",
    TIME_TO: "12:00",
    PERIOD_START: "2",
    PERIOD_END: "4",
    Q1: "S",
    TEACHER: [
      {
        TEACHER_CODE: "663439",
        FIRST_THAI_NAME: "สุธิรา",
        LAST_THAI_NAME: "เบญจานุกรม",
      },
    ],
  },
  {
    F_ROWID_REGIS_D: "60b352ef3155e",
    F_ROWID_SUBJECT: "5cb803f989728",
    F_ROWID_TABTEACH: "TTI12564119600",
    YEAR: "2564",
    TERM: "1",
    SUBJECT_CODE: "TECE504",
    SECTION: "01",
    REGIS_TYPE: "C",
    REGIS_TYPE_TEXT: "Credit",
    SUBJECT_NAME: "ปฐพีกลศาสตร์",
    SUBJECT_TYPE: "ภาคปกติ",
    CREDIT: "3(3-0-6)",
    TOTAL_CREDIT: "3",
    T_HOUR: "3",
    P_HOUR: "0",
    S_HOUR: "6",
    STATUS: "00",
    STATUS_TEXT: null,
    VOLUME: "1",
    DAY_CODE: "5",
    DAY_NAME: "ศ.",
    ROOM_CODE: "18/3203",
    TIME_FROM: "09:00",
    TIME_TO: "12:00",
    PERIOD_START: "2",
    PERIOD_END: "4",
    Q1: "S",
    TEACHER: [
      {
        TEACHER_CODE: "141001",
        FIRST_THAI_NAME: "สุชิรา",
        LAST_THAI_NAME: "นวลกำแหง",
      },
    ],
  },
  {
    F_ROWID_REGIS_D: "60b352ef3321d",
    F_ROWID_SUBJECT: "5cb80438bef52",
    F_ROWID_TABTEACH: "TTI12564119601",
    YEAR: "2564",
    TERM: "1",
    SUBJECT_CODE: "TECE505",
    SECTION: "01",
    REGIS_TYPE: "C",
    REGIS_TYPE_TEXT: "Credit",
    SUBJECT_NAME: "ปฏิบัติการปฐพีกลศาสตร์",
    SUBJECT_TYPE: "ภาคปกติ",
    CREDIT: "1(0-3-2)",
    TOTAL_CREDIT: "1",
    T_HOUR: "0",
    P_HOUR: "3",
    S_HOUR: "2",
    STATUS: "00",
    STATUS_TEXT: null,
    VOLUME: "1",
    DAY_CODE: "5",
    DAY_NAME: "ศ.",
    ROOM_CODE: "18/3203",
    TIME_FROM: "13:00",
    TIME_TO: "16:00",
    PERIOD_START: "5",
    PERIOD_END: "7",
    Q1: "S",
    TEACHER: [
      {
        TEACHER_CODE: "141001",
        FIRST_THAI_NAME: "สุชิรา",
        LAST_THAI_NAME: "นวลกำแหง",
      },
    ],
  },
  {
    F_ROWID_REGIS_D: "60b352ef26378",
    F_ROWID_SUBJECT: "574bef2f6b340",
    F_ROWID_TABTEACH: "TTI12564120002",
    YEAR: "2564",
    TERM: "1",
    SUBJECT_CODE: "GESC103",
    SECTION: "07",
    REGIS_TYPE: "C",
    REGIS_TYPE_TEXT: "Credit",
    SUBJECT_NAME: "เทคโนโลยีสารสนเทศเพื่อชีวิต",
    SUBJECT_TYPE: "ภาคปกติ",
    CREDIT: "3(3-0-6)",
    TOTAL_CREDIT: "3",
    T_HOUR: "3",
    P_HOUR: "0",
    S_HOUR: "6",
    STATUS: "00",
    STATUS_TEXT: null,
    VOLUME: "2",
    DAY_CODE: "1",
    DAY_NAME: "จ.",
    ROOM_CODE: "24307",
    TIME_FROM: "13:00",
    TIME_TO: "16:00",
    PERIOD_START: "5",
    PERIOD_END: "7",
    Q1: "B",
    TEACHER: [
      {
        TEACHER_CODE: "656296",
        FIRST_THAI_NAME: "เขมปริต",
        LAST_THAI_NAME: "ขุนราชเสนา",
      },
    ],
  },
];
