export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_CLEAR_ERROR = "AUTH_CLEAR_ERROR";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
export const AUTH_NOTIFICATION_LOGOUT = "AUTH_NOTIFICATION_LOGOUT";
export const AUTH_CLOSE_NOTIFICATION_LOGOUT = "AUTH_CLOSE_NOTIFICATION_LOGOUT";
export const SET_NOTIFICATION_TIME = "SET_NOTIFICATION_TIME";
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";

export const REFRESH_ACCESS_TOKEN_FROM_SERVER_START =
  "REFRESH_ACCESS_TOKEN_FROM_SERVER_START";
export const REFRESH_ACCESS_TOKEN_FROM_SERVER_SUCCESS =
  "REFRESH_ACCESS_TOKEN_FROM_SERVER_SUCCESS";
export const REFRESH_ACCESS_TOKEN_FROM_SERVER_FAIL =
  "REFRESH_ACCESS_TOKEN_FROM_SERVER_FAIL";

export const TICK = "TICK";

export const SET_TIME_IN_MODAL = "SET_TIME_IN_MODAL";

export const SET_LANGUAGE = "SET_LANGUAGE";
export const RESET_LANGUAGE = "RESET_LANGUAGE";
