export default [
  {
    ID: "1",
    F_ROWID_REGIS_D: "60b38b053fba8",
    F_ROWID_SUBJECT: "5cca5f72d39f2",
    F_ROWID_TABTEACH: "TTI12564118669",
    YEAR: "2564",
    TERM: "1",
    SUBJECT_CODE: "EDPE302",
    SECTION: "01",
    REGIS_TYPE: "C",
    REGIS_TYPE_TEXT: "Credit",
    SUBJECT_NAME: "วอลเลย์บอล",
    SUBJECT_TYPE: "ภาคปกติ",
    CREDIT: "1(0-2-1)",
    TOTAL_CREDIT: "1",
    T_HOUR: "0",
    P_HOUR: "2",
    S_HOUR: "1",
    STATUS: "00",
    STATUS_TEXT: null,
    VOLUME: "3",
    DAY_CODE: "5",
    DAY_NAME: "ศ.",
    ROOM_CODE: "โรงยิม1",
    TIME_FROM: "13:00",
    TIME_TO: "15:00",
    PERIOD_START: "5",
    PERIOD_END: "6",
    TEACHER: [
      {
        TEACHER_CODE: "655152",
        FIRST_THAI_NAME: "พลากร",
        LAST_THAI_NAME: "ชาญณรงค์",
      },
    ],
  },
  {
    ID: "2",
    F_ROWID_REGIS_D: "60b38b0542c4d",
    F_ROWID_SUBJECT: "5cca5eff9b698",
    F_ROWID_TABTEACH: "TTI12564118707",
    YEAR: "2564",
    TERM: "1",
    SUBJECT_CODE: "EDPE101",
    SECTION: "01",
    REGIS_TYPE: "C",
    REGIS_TYPE_TEXT: "Credit",
    SUBJECT_NAME: "กายวิภาคศาสตร์และสรีรวิทยา",
    SUBJECT_TYPE: "ภาคปกติ",
    CREDIT: "3(2-2-5)",
    TOTAL_CREDIT: "3",
    T_HOUR: "2",
    P_HOUR: "2",
    S_HOUR: "5",
    STATUS: "00",
    STATUS_TEXT: null,
    VOLUME: "3",
    DAY_CODE: "2",
    DAY_NAME: "อ.",
    ROOM_CODE: "20102",
    TIME_FROM: "13:00",
    TIME_TO: "17:00",
    PERIOD_START: "5",
    PERIOD_END: "8",
    TEACHER: [
      {
        TEACHER_CODE: "654026",
        FIRST_THAI_NAME: "ปรเมษฐ์",
        LAST_THAI_NAME: "วงษ์พุทธิชัย",
      },
    ],
  },
  {
    ID: "3",
    F_ROWID_REGIS_D: "60b38b0554072",
    F_ROWID_SUBJECT: "5cca5f3982725",
    F_ROWID_TABTEACH: "TTI12564118731",
    YEAR: "2564",
    TERM: "1",
    SUBJECT_CODE: "EDPE106",
    SECTION: "01",
    REGIS_TYPE: "C",
    REGIS_TYPE_TEXT: "Credit",
    SUBJECT_NAME: "การเคลื่อนไหวพื้นฐาน",
    SUBJECT_TYPE: "ภาคปกติ",
    CREDIT: "2(1-2-3)",
    TOTAL_CREDIT: "2",
    T_HOUR: "1",
    P_HOUR: "2",
    S_HOUR: "3",
    STATUS: "00",
    STATUS_TEXT: null,
    VOLUME: "2",
    DAY_CODE: "2",
    DAY_NAME: "อ.",
    ROOM_CODE: "26101",
    TIME_FROM: "09:00",
    TIME_TO: "12:00",
    PERIOD_START: "2",
    PERIOD_END: "4",
    TEACHER: [
      {
        TEACHER_CODE: "654026",
        FIRST_THAI_NAME: "ปรเมษฐ์",
        LAST_THAI_NAME: "วงษ์พุทธิชัย",
      },
    ],
  },
  {
    ID: "4",
    F_ROWID_REGIS_D: "60b38b055b565",
    F_ROWID_SUBJECT: "5cca5f98ad221",
    F_ROWID_TABTEACH: "TTI12564118799",
    YEAR: "2564",
    TERM: "1",
    SUBJECT_CODE: "EDPE304",
    SECTION: "01",
    REGIS_TYPE: "C",
    REGIS_TYPE_TEXT: "Credit",
    SUBJECT_NAME: "ตะกร้อ",
    SUBJECT_TYPE: "ภาคปกติ",
    CREDIT: "1(0-2-1)",
    TOTAL_CREDIT: "1",
    T_HOUR: "0",
    P_HOUR: "2",
    S_HOUR: "1",
    STATUS: "00",
    STATUS_TEXT: null,
    VOLUME: "2",
    DAY_CODE: "5",
    DAY_NAME: "ศ.",
    ROOM_CODE: "สนามตะกร้อ",
    TIME_FROM: "10:00",
    TIME_TO: "12:00",
    PERIOD_START: "3",
    PERIOD_END: "4",
    TEACHER: [
      {
        TEACHER_CODE: "659386",
        FIRST_THAI_NAME: "สลักจิตร",
        LAST_THAI_NAME: "คณะฤทธิ์",
      },
    ],
  },
  {
    ID: "5",
    F_ROWID_REGIS_D: "60b38b0548a3b",
    F_ROWID_SUBJECT: "5cbe8825b1bba",
    F_ROWID_TABTEACH: "TTI12564119657",
    YEAR: "2564",
    TERM: "1",
    SUBJECT_CODE: "GETL101",
    SECTION: "02",
    REGIS_TYPE: "C",
    REGIS_TYPE_TEXT: "Credit",
    SUBJECT_NAME: "ทักษะการพูดและการฟังภาษาอังกฤษ",
    SUBJECT_TYPE: "ภาคปกติ",
    CREDIT: "3(2-2-5)",
    TOTAL_CREDIT: "3",
    T_HOUR: "2",
    P_HOUR: "2",
    S_HOUR: "5",
    STATUS: "00",
    STATUS_TEXT: null,
    VOLUME: "1",
    DAY_CODE: "3",
    DAY_NAME: "พ.",
    ROOM_CODE: "14505",
    TIME_FROM: "08:00",
    TIME_TO: "12:00",
    PERIOD_START: "1",
    PERIOD_END: "4",
    TEACHER: [
      {
        TEACHER_CODE: "656262",
        FIRST_THAI_NAME: "นงลักษ์",
        LAST_THAI_NAME: "ยุทธศิลปเสวี",
      },
    ],
  },
  {
    ID: "6",
    F_ROWID_REGIS_D: "60b38b0557b01",
    F_ROWID_SUBJECT: "5cbe86e76614b",
    F_ROWID_TABTEACH: "TTI12564119750",
    YEAR: "2564",
    TERM: "1",
    SUBJECT_CODE: "EDTE105",
    SECTION: "02",
    REGIS_TYPE: "C",
    REGIS_TYPE_TEXT: "Credit",
    SUBJECT_NAME: "คุณธรรม จริยธรรม จรรยาบรรณ และจิตวิญญาณความเป็นครู",
    SUBJECT_TYPE: "ภาคปกติ",
    CREDIT: "3(2-2-5)",
    TOTAL_CREDIT: "3",
    T_HOUR: "2",
    P_HOUR: "2",
    S_HOUR: "5",
    STATUS: "00",
    STATUS_TEXT: null,
    VOLUME: "1",
    DAY_CODE: "1",
    DAY_NAME: "จ.",
    ROOM_CODE: "ED404",
    TIME_FROM: "08:00",
    TIME_TO: "12:00",
    PERIOD_START: "1",
    PERIOD_END: "4",
    TEACHER: [
      {
        TEACHER_CODE: "652084",
        FIRST_THAI_NAME: "กานต์",
        LAST_THAI_NAME: "อัมพานนท์",
      },
    ],
  },
  {
    ID: "7",
    F_ROWID_REGIS_D: "60b38b054b6a6",
    F_ROWID_SUBJECT: "5cca5dd33cc5e",
    F_ROWID_TABTEACH: "TTI12564119864",
    YEAR: "2564",
    TERM: "1",
    SUBJECT_CODE: "EDPE201",
    SECTION: "02",
    REGIS_TYPE: "C",
    REGIS_TYPE_TEXT: "Credit",
    SUBJECT_NAME: "รากฐานพลศึกษา ปรัชญาและหลักการพลศึกษา",
    SUBJECT_TYPE: "ภาคปกติ",
    CREDIT: "2(1-2-3)",
    TOTAL_CREDIT: "2",
    T_HOUR: "1",
    P_HOUR: "2",
    S_HOUR: "3",
    STATUS: "00",
    STATUS_TEXT: null,
    VOLUME: "3",
    DAY_CODE: "1",
    DAY_NAME: "จ.",
    ROOM_CODE: "20101",
    TIME_FROM: "13:00",
    TIME_TO: "16:00",
    PERIOD_START: "5",
    PERIOD_END: "7",
    TEACHER: [
      {
        TEACHER_CODE: "561594",
        FIRST_THAI_NAME: "ภาพพิมพ์",
        LAST_THAI_NAME: "วังบุญคง",
      },
    ],
  },
  {
    ID: "8",
    F_ROWID_REGIS_D: "60b38b054e329",
    F_ROWID_SUBJECT: "5cca5fba6802a",
    F_ROWID_TABTEACH: "TTI12564119865",
    YEAR: "2564",
    TERM: "1",
    SUBJECT_CODE: "EDPE307",
    SECTION: "01",
    REGIS_TYPE: "C",
    REGIS_TYPE_TEXT: "Credit",
    SUBJECT_NAME: "กระบี่กระบอง",
    SUBJECT_TYPE: "ภาคปกติ",
    CREDIT: "1(0-2-1)",
    TOTAL_CREDIT: "1",
    T_HOUR: "0",
    P_HOUR: "2",
    S_HOUR: "1",
    STATUS: "00",
    STATUS_TEXT: null,
    VOLUME: "2",
    DAY_CODE: "5",
    DAY_NAME: "ศ.",
    ROOM_CODE: "โรงยิม2/2",
    TIME_FROM: "08:00",
    TIME_TO: "10:00",
    PERIOD_START: "1",
    PERIOD_END: "2",
    TEACHER: [
      {
        TEACHER_CODE: "561593",
        FIRST_THAI_NAME: "พงษ์วรินทร์",
        LAST_THAI_NAME: "เต็งยี่",
      },
    ],
  },
  {
    ID: "9",
    F_ROWID_REGIS_D: "60b38b0550eb0",
    F_ROWID_SUBJECT: "5cbe80f1eb2f8",
    F_ROWID_TABTEACH: "TTI12564119881",
    YEAR: "2564",
    TERM: "1",
    SUBJECT_CODE: "EDPS201",
    SECTION: "06",
    REGIS_TYPE: "C",
    REGIS_TYPE_TEXT: "Credit",
    SUBJECT_NAME: "จิตวิทยาสำหรับครู",
    SUBJECT_TYPE: "ภาคปกติ",
    CREDIT: "3(2-2-5)",
    TOTAL_CREDIT: "3",
    T_HOUR: "2",
    P_HOUR: "2",
    S_HOUR: "5",
    STATUS: "00",
    STATUS_TEXT: null,
    VOLUME: "3",
    DAY_CODE: "4",
    DAY_NAME: "พฤ.",
    ROOM_CODE: "ED303",
    TIME_FROM: "13:00",
    TIME_TO: "17:00",
    PERIOD_START: "5",
    PERIOD_END: "8",
    TEACHER: [
      {
        TEACHER_CODE: "148002",
        FIRST_THAI_NAME: "สุเทพ",
        LAST_THAI_NAME: "ธรรมะตระกูล",
      },
    ],
  },
  {
    ID: "10",
    F_ROWID_REGIS_D: "60b38b054594a",
    F_ROWID_SUBJECT: "5cbe7dfba3077",
    F_ROWID_TABTEACH: "TTI12564120045",
    YEAR: "2564",
    TERM: "1",
    SUBJECT_CODE: "EDLA101",
    SECTION: "01",
    REGIS_TYPE: "C",
    REGIS_TYPE_TEXT: "Credit",
    SUBJECT_NAME: "ภาษาเพื่อการสื่อสาร",
    SUBJECT_TYPE: "ภาคปกติ",
    CREDIT: "3(2-2-5)",
    TOTAL_CREDIT: "3",
    T_HOUR: "2",
    P_HOUR: "2",
    S_HOUR: "5",
    STATUS: "00",
    STATUS_TEXT: null,
    VOLUME: "1",
    DAY_CODE: "4",
    DAY_NAME: "พฤ.",
    ROOM_CODE: "หมื่นจง",
    TIME_FROM: "08:00",
    TIME_TO: "12:00",
    PERIOD_START: "1",
    PERIOD_END: "4",
    TEACHER: [
      {
        TEACHER_CODE: "658357",
        FIRST_THAI_NAME: "อโณทัย พลเยี่ยม",
        LAST_THAI_NAME: "เพชรแสง",
      },
      {
        TEACHER_CODE: "660394",
        FIRST_THAI_NAME: "พิชญา",
        LAST_THAI_NAME: "เชี่ยวภาษา",
      },
    ],
  },
];
